name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict
      
      - name: Run Unit Tests
        run: xcodebuild test -scheme Cicd -destination 'platform=iOS Simulator,name=iPhone 16' -enableCodeCoverage YES
